### ISSUE TITLE
Manage inter-processor communication

### ISSUE THREAD

**Issue by iac26** [EPFLRocketTeam/WildhornAV#7]

**Comment by iac26** [comment]
Use openAMP on the cortex m4 and rpmsg in linux

**Comment by ofacklam** [comment]
Andrea Guerrieri from LAP said that openAMP might be overkill for this. It could come with many complex features and issues. 
But it could still be worth a try!

**Comment by iac26** [comment]
My idea is to use openAMP to create virtual serial connections between the cortex-m4 and the linux kernel -> on linux it appears as a serial device easily interfaced in python or c 
on the cortex-m4 it can be interfaced with the generic device driver
